import type { ShopItem, Powerup } from '../types/game.types';

export const SHOP_CATALOG: ShopItem[] = [
  // Skins
  {
    id: 'default',
    name: 'Default',
    type: 'skin',
    description: 'Classic look',
    cost: 0,
    preview: '🔵',
    rarity: 'common',
  },
  {
    id: 'skin_ninja',
    name: 'Ninja',
    type: 'skin',
    description: 'Silent and swift',
    cost: 100,
    preview: '🥷',
    rarity: 'common',
  },
  {
    id: 'skin_robot',
    name: 'Cyber Runner',
    type: 'skin',
    description: 'Futuristic style',
    cost: 150,
    preview: '🤖',
    rarity: 'rare',
  },
  {
    id: 'skin_ghost',
    name: 'Phantom',
    type: 'skin',
    description: 'Mysterious presence',
    cost: 200,
    preview: '👻',
    rarity: 'epic',
  },
  {
    id: 'skin_flame',
    name: 'Blaze',
    type: 'skin',
    description: 'Hot-headed runner',
    cost: 250,
    preview: '🔥',
    rarity: 'epic',
  },
  {
    id: 'skin_ice',
    name: 'Frost',
    type: 'skin',
    description: 'Cool and collected',
    cost: 250,
    preview: '❄️',
    rarity: 'epic',
  },

  // Powerups
  {
    id: 'powerup_speed',
    name: 'Speed Surge',
    type: 'powerup',
    description: '+50% movement speed for 5 seconds',
    cost: 50,
    preview: '⚡',
    rarity: 'common',
  },
  {
    id: 'powerup_smoke',
    name: 'Smoke Bomb',
    type: 'powerup',
    description: 'Create vision-blocking cloud for 8 seconds',
    cost: 75,
    preview: '💨',
    rarity: 'common',
  },
  {
    id: 'powerup_decoy',
    name: 'Decoy',
    type: 'powerup',
    description: 'Spawn fake player to distract the bot',
    cost: 100,
    preview: '🎭',
    rarity: 'rare',
  },
  {
    id: 'powerup_timeslow',
    name: 'Time Warp',
    type: 'powerup',
    description: 'Slow bot by 50% for 6 seconds',
    cost: 150,
    preview: '⏰',
    rarity: 'epic',
  },
  {
    id: 'powerup_ghost',
    name: 'Ghost Walk',
    type: 'powerup',
    description: 'Walk through walls for 3 seconds',
    cost: 200,
    preview: '👻',
    rarity: 'legendary',
  },

  // Pets
  {
    id: 'pet_dog',
    name: 'Loyal Pup',
    type: 'pet',
    description: 'Warns when bot is nearby',
    cost: 200,
    preview: '🐕',
    rarity: 'rare',
  },
  {
    id: 'pet_cat',
    name: 'Shadow Cat',
    type: 'pet',
    description: 'Grants speed boost ability',
    cost: 250,
    preview: '🐈',
    rarity: 'rare',
  },
  {
    id: 'pet_bird',
    name: 'Scout Bird',
    type: 'pet',
    description: 'Provides distraction ability',
    cost: 300,
    preview: '🐦',
    rarity: 'epic',
  },
];

export const POWERUP_DEFINITIONS: Record<string, Powerup> = {
  powerup_speed: {
    id: 'powerup_speed',
    name: 'Speed Surge',
    description: '+50% movement speed',
    cost: 50,
    duration: 5,
    icon: '⚡',
    maxUses: 2,
    effect: {
      type: 'speed_boost',
      magnitude: 1.5,
      duration: 5,
    },
  },
  powerup_smoke: {
    id: 'powerup_smoke',
    name: 'Smoke Bomb',
    description: 'Vision-blocking cloud',
    cost: 75,
    duration: 8,
    icon: '💨',
    maxUses: 2,
    effect: {
      type: 'invisibility',
      duration: 8,
    },
  },
  powerup_decoy: {
    id: 'powerup_decoy',
    name: 'Decoy',
    description: 'Spawn fake player',
    cost: 100,
    icon: '🎭',
    maxUses: 1,
    effect: {
      type: 'decoy',
      duration: 10,
    },
  },
  powerup_timeslow: {
    id: 'powerup_timeslow',
    name: 'Time Warp',
    description: 'Slow bot movement',
    cost: 150,
    duration: 6,
    icon: '⏰',
    maxUses: 1,
    effect: {
      type: 'time_slow',
      magnitude: 0.5,
      duration: 6,
    },
  },
  powerup_ghost: {
    id: 'powerup_ghost',
    name: 'Ghost Walk',
    description: 'Walk through walls',
    cost: 200,
    duration: 3,
    icon: '👻',
    maxUses: 1,
    effect: {
      type: 'wall_phase',
      duration: 3,
    },
  },
};
